<a href="https://colab.research.google.com/github/VARSHITHA-DARMINI/23CSBTB30/blob/main/Arrays.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
arr1=np.array([3,4,5,6])
print(arr1)
print(type(arr1))

[3 4 5 6]
<class 'numpy.ndarray'>


In [2]:
arr2=np.zeros((2,3))
print(arr2)
print(type(arr2))


[[0. 0. 0.]
 [0. 0. 0.]]
<class 'numpy.ndarray'>


In [3]:
arr3=np.array([[1,2,3],[5,6,7],[3,6,7]])
print(arr3)
print(type(arr3))

[[1 2 3]
 [5 6 7]
 [3 6 7]]
<class 'numpy.ndarray'>


In [4]:
arr4=np.array([[1, 2], [3, 4]])
print(arr4)
print(type(arr4))

[[1 2]
 [3 4]]
<class 'numpy.ndarray'>


In [5]:
dtype = [('name', 'S10'), ('age', 'i4')]
values = [('Alice', 25), ('Bob', 30)]
arr5 = np.array(values, dtype=dtype)
print(arr5)
print(type(arr5))

[(b'Alice', 25) (b'Bob', 30)]
<class 'numpy.ndarray'>


In [6]:
arr6 = np.matrix([[1, 2], [3, 4]])
print(arr6)
print(type(arr6))

[[1 2]
 [3 4]]
<class 'numpy.matrix'>


In [10]:
import numpy as np
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
result = array1 * array2
print("Multiplication Result:", result)


Multiplication Result: [ 5 12 21 32]


In [11]:
import numpy as np
array1 = np.array([9, 7, 3, 4])
array2 = np.array([5, 6, 7, 7])
result = array1 / array2
print("Division Result:", result)

Division Result: [1.8        1.16666667 0.42857143 0.57142857]


In [12]:
import numpy as np
array1 = np.array([1, 2, 3, 4])
array2 = np.array([5, 6, 7, 8])
result = array1 ^array2
print("Power Result:", result)

Power Result: [ 4  4  4 12]


In [13]:
 arr= f"Addition of Two: {array1} + {array2} = {array1 + array2}"
print("\n" + arr)


Addition of Two: [1 2 3 4] + [5 6 7 8] = [ 6  8 10 12]


In [14]:

sin = np.sin(array1)
log = np.log(array1 + 1)  # Adding 1 to avoid log(0)
log2 = np.log2(array1 + 1)
exp = np.exp(array1)

print( sin)
print(log)
print(log2)
print(expr)


[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]
[0.69314718 1.09861229 1.38629436 1.60943791]
[1.         1.5849625  2.         2.32192809]


NameError: name 'expr' is not defined